- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-fwaas-v2-dsvm-tempest
        - neutron-fwaas-functional
        - legacy-grenade-dsvm-neutron-fwaas-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - neutron-fwaas-v2-dsvm-tempest-multinode:
            voting: false
    gate:
      jobs:
        - neutron-fwaas-v2-dsvm-tempest
        - neutron-fwaas-functional
    experimental:
      jobs:
        - neutron-fwaas-fullstack

- job:
    name: neutron-fwaas-functional
    parent: neutron-functional
    vars:
      project_name: neutron-fwaas

- job:
    name: neutron-fwaas-fullstack
    parent: neutron-fullstack
    vars:
      project_name: neutron-fwaas


- job:
    name: neutron-fwaas-v2-dsvm-tempest
    parent: devstack-tempest
    roles:
      - zuul: openstack/devstack
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/neutron-fwaas
      - openstack/tempest
    vars:
      tox_envlist: all-plugin
      tempest_test_regex: ^neutron_fwaas\.
      devstack_plugins:
        neutron: https://opendev.org/openstack/neutron.git
        neutron-fwaas: https://opendev.org/openstack/neutron-fwaas.git
      devstack_services:
        q-fwaas-v2: true
      devstack_localrc:
        USE_PYTHON3: true
        NETWORK_API_EXTENSIONS: "agent,binding,dhcp_agent_scheduler,external-net,ext-gw-mode,extra_dhcp_opts,quotas,router,security-group,subnet_allocation,network-ip-availability,auto-allocated-topology,timestamp_core,tag,service-type,rbac-policies,standard-attr-description,pagination,sorting,project-id,fwaas_v2"

- job:
    name: neutron-fwaas-v2-dsvm-tempest-multinode
    parent: tempest-multinode-full-py3
    roles:
      - zuul: openstack/devstack
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/neutron-fwaas
      - openstack/tempest
    vars:
      tox_envlist: all-plugin
      tempest_test_regex: ^neutron_fwaas\.
      devstack_plugins:
        neutron: https://opendev.org/openstack/neutron.git
        neutron-fwaas: https://opendev.org/openstack/neutron-fwaas.git
      devstack_services:
        q-fwaas-v2: true
      devstack_localrc:
        NETWORK_API_EXTENSIONS: "agent,binding,dhcp_agent_scheduler,external-net,ext-gw-mode,extra_dhcp_opts,quotas,router,security-group,subnet_allocation,network-ip-availability,auto-allocated-topology,timestamp_core,tag,service-type,rbac-policies,standard-attr-description,pagination,sorting,project-id,fwaas_v2"
    group-vars:
      subnode:
        devstack_services:
          q-agt: true
        devstack_localrc:
          USE_PYTHON3: true
        devstack_local_conf:
          post-config:
            # NOTE(slaweq): We can get rid of this hardcoded absolute path when
            # devstack-tempest job will be switched to use lib/neutron instead of
            # lib/neutron-legacy
            "/$NEUTRON_CORE_PLUGIN_CONF":
              ovs:
                tunnel_bridge: br-tun
                bridge_mappings: public:br-ex
