- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - legacy-neutron-fwaas-v2-dsvm-tempest
        - legacy-neutron-fwaas-dsvm-functional
        - legacy-grenade-dsvm-neutron-fwaas-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-neutron-fwaas-v2-dsvm-tempest-multinode:
            voting: false
    gate:
      jobs:
        - legacy-neutron-fwaas-v2-dsvm-tempest
        - legacy-neutron-fwaas-dsvm-functional
    experimental:
      jobs:
        - neutron-fwaas-fullstack

- job:
    name: neutron-fwaas-fullstack
    parent: neutron-fullstack
    vars:
      project_name: neutron-fwaas
